on:
  push:
    tags:
      - '*'

name: Upload Release Assets

jobs:
  build:
    name: Upload Release Assets
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build frontend
        run: cd frontend && yarn install && yarn build
      - name: Build backend
        run: |
          ./gradlew buildGraph
          ./gradlew build -x buildGraph -x distTar -x distZip
        env:
          EVE_ROUTE_DB: jdbc:sqlite:/tmp/sqlite.db
          EVE_ROUTE_CLIENT_ID:
          EVE_ROUTE_CLIENT_SECRET:
          EVE_ROUTE_CALLBACK:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/libs/eve-route-${{ steps.get_version.outputs.VERSION }}.jar
            build/libs/eve-route-${{ steps.get_version.outputs.VERSION }}.war
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
